### ISSUE TITLE
Stable-Diffusionでeagle-pnginfoを導入する前に生成した画像をeagleに保存する方法

### ISSUE THREAD

**Issue by SuperBANANAghost** [bbc-mc/sdweb-eagle-pnginfo#15]
私は過去にeagle-pnginfoを通さずに生成した画像が6GBあります。これらをこの拡張機能を通して保存する方法はありますか？
もしないなら、outputを参照してeagle-pnginfoを動作させる機能を追加して欲しいです。

**Comment by bbc-mc** [comment]
こんにちは
拙作ですが、こちらでどうでしょう
https://github.com/bbc-mc/sdweb-eagle-transfer

**Comment by SuperBANANAghost** [comment]
調べ不足でした
ありがとうございます！
