### ISSUE TITLE
"Send all images to Eagle" is not displayed

### ISSUE THREAD

**Issue by kkkirin** [bbc-mc/sdweb-eagle-pnginfo#2]
The "Send all image to Eagle" field does not appear at the bottom of "all image to Eagle".
![FDFC9568-D743-4078-A8FC-2A3908D9696F](https://user-images.githubusercontent.com/96969970/211251475-3ba133bb-1d8e-4e9c-9795-c24089208c70.jpeg)
New WEBUI installed on 1/8/2011.
I think it was displayed in the previous UI

**Comment by bbc-mc** [comment]
Hi, what "field" are you mentiond?
Button? Checkbox?
I thing there is "Send all image to Eagle" Checkbox on your image ...

It looks same as UI components in image of yours and https://github.com/bbc-mc/sdweb-eagle-pnginfo/blob/master/misc/sss09.png (from readme).
This repo is not changed from 1/Dec and image also.

**Comment by kkkirin** [comment]
Thanks for the reply! I remember that the image I attached has an arrow pointing to a box where you can enter the ID "FolderID on Eagle (option)".
I'll post the image again
I am quoting from a sample setting!
![5E92982F-C052-4DC7-B831-467EAC9A341F](https://user-images.githubusercontent.com/96969970/211319562-c4535b51-9d7d-467a-84ec-366b1e4145be.jpeg)
https://github.com/bbc-mc/sdweb-eagle-pnginfo#:~:text=name%20dont%20exists.-,setting%20sample,-Settings

I don't see "FolderID on Eagle (option) "on my screen.

Sorry for the lack of clarity.
Thank you very much in advance for your help.

**Comment by bbc-mc** [comment]
Thanks, make sence.

`FolderID on Eagle (option)` is changed and enhanced to `(option) FolderID or FolderName on Eagle`.
and change position of field to below.
You can find this field on your fiest image.

You can use this field by "ID" or "Name" or mix of them.

p.s. I found README has doubled description ... I'll fix that.
README 内に `FolderID on Eagle` の記述が残っていてわかりにくかったですね、修正します。

**Comment by kkkirin** [comment]
Thanks for the reply.
"Outside Eagle server connection (url:port)"　It seems it was the extra text that was causing the problem.
Resolved.
Thanks again for all your great extensions!
